version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_rentx
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3000:3000
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local

# Verificar se já existe container criado e removê-lo:
# docker ps
# docker stop <id do container>
# docker rm <id do container>

# Executar docker compose pelo terminal:
# docker-compose up

# Verificar IP do container:
# docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' rentx
# OU
# docker exec database_rentx cat /etc/hosts