openapi: 3.0.0
info:
    title: Sample API
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 0.1.9


paths:
  /categories:
    post:
        tags:
          - "Category"
        summary: Create a category
        description: Create a new category
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            name:
                                type: string
                                example: SUV
                            description: 
                                type: string
                                example: Category of cars SUV
        responses:
            '201':
                description: Created
            '500':
                description: Category already exists     
    get:
        tags:
          - "Category"
        summary: List all categories.
        description: List all categories.
        responses:
            '200': # status code
                description: Success
                content:
                    application/json:
                        schema: 
                            type: array
                            items: 
                                type: object
                                properties:
                                    name: 
                                        type: string
                                    description:
                                        type: string

